#! /bin/sh
set -e

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3 \
                    libblas.so.3-x86_64-linux-gnu \
	            /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 100

update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so.3 \
                    liblapack.so.3-x86_64-linux-gnu \
	            /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3 100

update-alternatives --install /usr/lib/x86_64-linux-gnu/libopenblas.so.0 \
                    libopenblas.so.0-x86_64-linux-gnu \
	            /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so.0 100



exit 0
